spring:
  datasource:
    data-username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/takeaway_applet?useSSL=false&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
      druid:
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        max-active: 50
        # 获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.myblog.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

#redis
redis:
  host: localhost
  port: 6379
  #超时时间
  timeout: 10
  #最大连接数
  poolMaxTotal: 1000
  #最大空闲连接数
  poolMaxIdle: 500
  #最大等待时间
  poolMaxWait: 500